### ISSUE TITLE
Reusing namespace ODRL?

### ISSUE THREAD

**Issue by clange** [dpvcg/dpv#11]
https://dpvcg.github.io/dpv/#namespaces mentions the ODRL namespace. However, [the actual implementation doesn't make any reference to ODRL](https://github.com/dpvcg/dpv/search?q=odrl).

Is an alignment with ODRL planned? I see some things that ODRL and DPV have in common. E.g., DPV defines "Processing" as "The processing performed on personal data", and ODRL says "An Action class indicates an operation that can be exercised on an Asset." And "anonymization" only makes sense on personal data, doesn't it?

Background: I am the maintainer of the [International Data Spaces (IDS) Information Model](https://github.com/International-Data-Spaces-Association/InformationModel/) and have some plans to align the IDS Information Model, which already is an extension of ODRL, with DPV.

**Comment by coolharsh55** [comment]
Hello, yes, aligning DPV with ODRL, or creating a DPV-profile for ODRL, or vice-versa : is definitely within the scope and interest of the group. I think your example represents a good way to align ODRL with DPV. We had ODRL and PROV reference in v0.1, but decided to remove those because of potential consequences on inference, and also because of wider questions as to why all concepts are not aligned. My suggestion would be to represent this alignment external to the actual vocabulary (at least initially). As for your existing work - you are welcome to propose, suggest, and work on this :) I know @besteves4 Beatriz is already working on ODRL and DPV for her research.

**Comment by coolharsh55** [comment]
Some points for consideration:

1) If `dpv:Processing` concepts are to be used as types of `odrl:Action`, then simply saying `dpv:Processing` is a sub-class of `odrl:Action` is not enough because DPV has sub-classes, not instances for Processing. So the import will end up creating many sub-classes of `odrl:Action`, whereas the ODRL taxonomy has instances of `odrl:Action`.
2) Would the existing relationships/contextual concepts for Processing, e.g. those allowing specification of large scale operations, or automated decision making, be usable in the intended ODRL application?
3) If there are more concepts to be imported from DPV into ODRL, e.g. Purpose or Legal Basis, does this cause issues in terms of semantics and interpretations?
4) Would a SKOS version of DPV be better suited for use with ODRL? This will enable maintaining the existing hierarchy (through SKOS) while permitting clean alignments (between existing sub-classes of dpv:Processing) to be instances of `odrl:Action`?

**Comment by coolharsh55** [comment]
Before closing this issue, and archiving the issue, see w3c/dpv#31 where ODRL and other mappings are discussed. tldr; Yes, getting from DPV to ODRL is in scope and under discussion.
