### ISSUE TITLE
Consistency in class naming

### ISSUE THREAD

**Issue by pchampin** [dpvcg/dpv#12]
It seems to me that the class `PersonalDataCategory` is wrongly named and should be renamed, probably to `PersonalData`. The rationale is that, from this name, one may infer that instances of the class are "categories", while my understanding is that the categories are actually the subclasses of this class (like "Financial" or "Historical").

What confirms this hint is the fact that one of the subclass is "SpecialCategoryPersonalData" (rather than "PersonalDataSpecialCategory").

Also, I believe that the immediate subclasses of <code>PersonalData<del>Category<del></code> should be named more explicitly `FinancialData`, `HistoricalData` and so on... In general, naming a class with an adjective is odd...

Intense bikeshedding, I know...

**Comment by coolharsh55** [comment]
In principle, I agree with both points. However, two 'burdens':

1. Changing one of the core concepts i.e. `PersonalDataCategory` -> `PersonalData` is a big change in terms of backwards compatibility (difficult)
2. Real world usage doesn't include suffixing all subsequence categories with "Data" (which is why they're named as such). But again, I agree in that in principle 'Internal' and 'External' are not good labels for terms.

Some form of a guide for concept naming and description texts needs to be established (doable)

Solution for 1 could be to keep the IRI the same `PersonalDataCategory` and only change the label to `PersonalData`. Same for subclasses.

**Comment by coolharsh55** [comment]
[FYI] We've moved the repo to https://github.com/w3c/dpv/ and I forgot to check the URL before replying. Could you please open this issue there so we can continue the discussion (I can copy my comment to yours). Thank you.

(also, have you joined DPVCG? If not, you're welcome to help resolve this)
