### ISSUE TITLE
Use 'rdf:Property' instead of 'rdfs:Property'

### ISSUE THREAD

**Issue by k----n** [dpvcg/dpv#6]
`rdfs:Property` is not defined in the rdfs namespace (https://www.w3.org/2000/01/rdf-schema#).

Instead it should be `rdf:Property`.

Let me know if you'd like me to submit a PR to fix this.

**Comment by coolharsh55** [comment]
Yes, this should be fixed in the upcoming commit. This also got pointed out in the [mailing list](https://lists.w3.org/Archives/Public/public-dpvcg/2020Aug/0004.html). I'm trying to streamline the process of vocabulary generation and HTML documentation generation so the process of fixing such errors and PRs would be more clear. Thanks for raising this.

**Comment by coolharsh55** [comment]
This is now corrected in commit 86e066c8b829f4437f425d847b94a1970b138b21 . This issue will be avoided in the future through use of https://github.com/coolharsh55/dpv-documentation which correctly uses `rdf:Property`.
